package tudbut.net.http;

/**
 * Content types
 */
public enum HTTPContentType {
    AAC(	"audio/aac"),
    ABW(	"application/x-abiword"),
    ARC(	"application/x-freearc"),
    AVI(	"video/x-msvideo"),
    AZW(	"application/vnd.amazon.ebook"),
    BIN(	"application/octet-stream"),
    BMP(	"image/bmp"),
    BZ(	    "application/x-bzip"),
    BZ2(	"application/x-bzip2"),
    CSH(	"application/x-csh"),
    CSS(	"text/css"),
    CSV(	"text/csv"),
    DOC(	"application/msword"),
    DOCX(	"application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
    EOT(	"application/vnd.ms-fontobject"),
    EPUB(	"application/epub+zip"),
    GZ(	    "application/gzip"),
    GIF(	"image/gif"),
    HTML(	"text/html"),
    HTTP(	"message/http"),
    ICO(	"image/vnd.microsoft.icon"),
    ICS(	"text/calendar"),
    JAR(	"application/java-archive"),
    JPG(	"image/jpeg"),
    JS( 	"text/javascript"),
    JSON(	"application/json"),
    JSONLD(	"application/ld+json"),
    MID(	"audio/midi"),
    MJS(	"text/javascript"),
    MP3(	"audio/mpeg"),
    MPEG(	"video/mpeg"),
    MPKG(	"application/vnd.apple.installer+xml"),
    ODP(	"application/vnd.oasis.opendocument.presentation"),
    ODS(	"application/vnd.oasis.opendocument.spreadsheet"),
    ODT(	"application/vnd.oasis.opendocument.text"),
    OGG(	"audio/ogg"),
    OGV(	"video/ogg"),
    OGX(	"application/ogg"),
    OPUS(	"audio/opus"),
    OTF(	"font/otf"),
    PNG(	"image/png"),
    PDF(	"application/pdf"),
    PHP(	"application/x-httpd-php"),
    PPT(	"application/vnd.ms-powerpoint"),
    PPTX(	"application/vnd.openxmlformats-officedocument.presentationml.presentation"),
    RAR(	"application/vnd.rar"),
    RTF(	"application/rtf"),
    SH(	    "application/x-sh"),
    SVG(	"image/svg+xml"),
    SWF(	"application/x-shockwave-flash"),
    TAR(	"application/x-tar"),
    TCN(	"text/tcn"),
    TCNMAP(	"application/tcnmap"),
    TS(	    "video/mp2t"),
    TTF(	"font/ttf"),
    TXT(	"text/plain"),
    VSD(	"application/vnd.visio"),
    WAV(	"audio/wav"),
    WEBA(	"audio/webm"),
    WEBM(	"video/webm"),
    WEBP(	"image/webp"),
    WOFF(	"font/woff"),
    WOFF2(	"font/woff2"),
    XHTML(	"application/xhtml+xml"),
    XLS(	"application/vnd.ms-excel"),
    XLSX(	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
    XML(	"application/xml"),
    XML_READABLE("text/xml"),
    XUL(	"application/vnd.mozilla.xul+xml"),
    ZIP(	"application/zip"),
    _3GP_AUDIO(	"audio/3gpp"),
    _3GP_VIDEO(	"video/3gpp"),
    _3G2_AUDIO(	"audio/3gpp2"),
    _3G2_VIDEO(	"video/3gpp2"),
    _7Z(	"application/x-7z-compressed"),
    ANY(	"*/*"),
    ;
    public final String asHeaderString;

    HTTPContentType(String asHeaderStringIn) {
        asHeaderString = asHeaderStringIn;
    }
}
